name: Build and Deploy
on: [push]
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout 🛎️
     uses: actions/checkout@v2.3.1
     with:
      persist-credentials: false

   - name: Install
     run: |
      sudo apt install git -y

   - name: Build
     run: |
      npm i
      npm run build
      npm run generate

   - name: Deploy
     uses: JamesIves/github-pages-deploy-action@3.7.1
     with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH: dist
      FOLDER: dist
      CLEAN: true
